coverage_service: cobertura_xml
xcodeproj: "AppConfig.xcodeproj"
scheme: "AppConfig"
configuration: Debug
source_directory: Sources
output_directory: xml_report
build_directory: "build"
binary_basename: "AppConfig Debug"
ignore:
  - Sources/Common/Resources/*