name: Deploy

on:
  pull_request:
    types: [opened]
    branches: [develop, master]

jobs:
  build:
    # Only when PR is closed and merged is true → That is, it starts only when merged
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: CircleCI Trigger on Pull Request
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          GHA_Action: auto-deploy
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}